### ISSUE TITLE
I was not able to locate the R code in this solution.

### ISSUE THREAD

**Issue by dkholo** [ShirinG/r-keras#1]
I was hoping to find a working version of the code in the solution. The primary problem I have is how image classes map to folders/files. So I was hoping to run a working version of the code.
I have downloaded the fruit image set.

**Comment by ShirinG** [comment]
Hi @dkholo,

The code I used this Dockerimage with is in this [Github repo](https://github.com/ShirinG/workshop_keras_tensorflow_r). It's a bit older and I've since worked on updating the Keras image but I assume it still works.
